// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/executor/commands"
)

type BridgeFactory struct {
	CreateBridgeStub        func(name string) error
	createBridgeMutex       sync.RWMutex
	createBridgeArgsForCall []struct {
		name string
	}
	createBridgeReturns struct {
		result1 error
	}
}

func (fake *BridgeFactory) CreateBridge(name string) error {
	fake.createBridgeMutex.Lock()
	fake.createBridgeArgsForCall = append(fake.createBridgeArgsForCall, struct {
		name string
	}{name})
	fake.createBridgeMutex.Unlock()
	if fake.CreateBridgeStub != nil {
		return fake.CreateBridgeStub(name)
	} else {
		return fake.createBridgeReturns.result1
	}
}

func (fake *BridgeFactory) CreateBridgeCallCount() int {
	fake.createBridgeMutex.RLock()
	defer fake.createBridgeMutex.RUnlock()
	return len(fake.createBridgeArgsForCall)
}

func (fake *BridgeFactory) CreateBridgeArgsForCall(i int) string {
	fake.createBridgeMutex.RLock()
	defer fake.createBridgeMutex.RUnlock()
	return fake.createBridgeArgsForCall[i].name
}

func (fake *BridgeFactory) CreateBridgeReturns(result1 error) {
	fake.CreateBridgeStub = nil
	fake.createBridgeReturns = struct {
		result1 error
	}{result1}
}

var _ commands.BridgeFactory = new(BridgeFactory)
