// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/executor/commands"
)

type LinkDeletor struct {
	DeleteLinkByNameStub        func(name string) error
	deleteLinkByNameMutex       sync.RWMutex
	deleteLinkByNameArgsForCall []struct {
		name string
	}
	deleteLinkByNameReturns struct {
		result1 error
	}
}

func (fake *LinkDeletor) DeleteLinkByName(name string) error {
	fake.deleteLinkByNameMutex.Lock()
	fake.deleteLinkByNameArgsForCall = append(fake.deleteLinkByNameArgsForCall, struct {
		name string
	}{name})
	fake.deleteLinkByNameMutex.Unlock()
	if fake.DeleteLinkByNameStub != nil {
		return fake.DeleteLinkByNameStub(name)
	} else {
		return fake.deleteLinkByNameReturns.result1
	}
}

func (fake *LinkDeletor) DeleteLinkByNameCallCount() int {
	fake.deleteLinkByNameMutex.RLock()
	defer fake.deleteLinkByNameMutex.RUnlock()
	return len(fake.deleteLinkByNameArgsForCall)
}

func (fake *LinkDeletor) DeleteLinkByNameArgsForCall(i int) string {
	fake.deleteLinkByNameMutex.RLock()
	defer fake.deleteLinkByNameMutex.RUnlock()
	return fake.deleteLinkByNameArgsForCall[i].name
}

func (fake *LinkDeletor) DeleteLinkByNameReturns(result1 error) {
	fake.DeleteLinkByNameStub = nil
	fake.deleteLinkByNameReturns = struct {
		result1 error
	}{result1}
}

var _ commands.LinkDeletor = new(LinkDeletor)
