// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/executor/commands"
)

type Locker struct {
	LockStub        func(string)
	lockMutex       sync.RWMutex
	lockArgsForCall []struct {
		arg1 string
	}
	UnlockStub        func(string)
	unlockMutex       sync.RWMutex
	unlockArgsForCall []struct {
		arg1 string
	}
}

func (fake *Locker) Lock(arg1 string) {
	fake.lockMutex.Lock()
	fake.lockArgsForCall = append(fake.lockArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.lockMutex.Unlock()
	if fake.LockStub != nil {
		fake.LockStub(arg1)
	}
}

func (fake *Locker) LockCallCount() int {
	fake.lockMutex.RLock()
	defer fake.lockMutex.RUnlock()
	return len(fake.lockArgsForCall)
}

func (fake *Locker) LockArgsForCall(i int) string {
	fake.lockMutex.RLock()
	defer fake.lockMutex.RUnlock()
	return fake.lockArgsForCall[i].arg1
}

func (fake *Locker) Unlock(arg1 string) {
	fake.unlockMutex.Lock()
	fake.unlockArgsForCall = append(fake.unlockArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.unlockMutex.Unlock()
	if fake.UnlockStub != nil {
		fake.UnlockStub(arg1)
	}
}

func (fake *Locker) UnlockCallCount() int {
	fake.unlockMutex.RLock()
	defer fake.unlockMutex.RUnlock()
	return len(fake.unlockArgsForCall)
}

func (fake *Locker) UnlockArgsForCall(i int) string {
	fake.unlockMutex.RLock()
	defer fake.unlockMutex.RUnlock()
	return fake.unlockArgsForCall[i].arg1
}

var _ commands.Locker = new(Locker)
