// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/executor/commands"
)

type MasterSetter struct {
	SetMasterStub        func(slave, master string) error
	setMasterMutex       sync.RWMutex
	setMasterArgsForCall []struct {
		slave  string
		master string
	}
	setMasterReturns struct {
		result1 error
	}
}

func (fake *MasterSetter) SetMaster(slave string, master string) error {
	fake.setMasterMutex.Lock()
	fake.setMasterArgsForCall = append(fake.setMasterArgsForCall, struct {
		slave  string
		master string
	}{slave, master})
	fake.setMasterMutex.Unlock()
	if fake.SetMasterStub != nil {
		return fake.SetMasterStub(slave, master)
	} else {
		return fake.setMasterReturns.result1
	}
}

func (fake *MasterSetter) SetMasterCallCount() int {
	fake.setMasterMutex.RLock()
	defer fake.setMasterMutex.RUnlock()
	return len(fake.setMasterArgsForCall)
}

func (fake *MasterSetter) SetMasterArgsForCall(i int) (string, string) {
	fake.setMasterMutex.RLock()
	defer fake.setMasterMutex.RUnlock()
	return fake.setMasterArgsForCall[i].slave, fake.setMasterArgsForCall[i].master
}

func (fake *MasterSetter) SetMasterReturns(result1 error) {
	fake.SetMasterStub = nil
	fake.setMasterReturns = struct {
		result1 error
	}{result1}
}

var _ commands.MasterSetter = new(MasterSetter)
