// This file was generated by counterfeiter
package fakes

import "github.com/cloudfoundry-incubator/ducati-daemon/executor/conditions"

type Context struct{}

var _ conditions.Context = new(Context)
