// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/executor"
)

type Condition struct {
	SatisfiedStub        func(context executor.Context) (bool, error)
	satisfiedMutex       sync.RWMutex
	satisfiedArgsForCall []struct {
		context executor.Context
	}
	satisfiedReturns struct {
		result1 bool
		result2 error
	}
	StringStub        func() string
	stringMutex       sync.RWMutex
	stringArgsForCall []struct{}
	stringReturns     struct {
		result1 string
	}
}

func (fake *Condition) Satisfied(context executor.Context) (bool, error) {
	fake.satisfiedMutex.Lock()
	fake.satisfiedArgsForCall = append(fake.satisfiedArgsForCall, struct {
		context executor.Context
	}{context})
	fake.satisfiedMutex.Unlock()
	if fake.SatisfiedStub != nil {
		return fake.SatisfiedStub(context)
	} else {
		return fake.satisfiedReturns.result1, fake.satisfiedReturns.result2
	}
}

func (fake *Condition) SatisfiedCallCount() int {
	fake.satisfiedMutex.RLock()
	defer fake.satisfiedMutex.RUnlock()
	return len(fake.satisfiedArgsForCall)
}

func (fake *Condition) SatisfiedArgsForCall(i int) executor.Context {
	fake.satisfiedMutex.RLock()
	defer fake.satisfiedMutex.RUnlock()
	return fake.satisfiedArgsForCall[i].context
}

func (fake *Condition) SatisfiedReturns(result1 bool, result2 error) {
	fake.SatisfiedStub = nil
	fake.satisfiedReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *Condition) String() string {
	fake.stringMutex.Lock()
	fake.stringArgsForCall = append(fake.stringArgsForCall, struct{}{})
	fake.stringMutex.Unlock()
	if fake.StringStub != nil {
		return fake.StringStub()
	} else {
		return fake.stringReturns.result1
	}
}

func (fake *Condition) StringCallCount() int {
	fake.stringMutex.RLock()
	defer fake.stringMutex.RUnlock()
	return len(fake.stringArgsForCall)
}

func (fake *Condition) StringReturns(result1 string) {
	fake.StringStub = nil
	fake.stringReturns = struct {
		result1 string
	}{result1}
}

var _ executor.Condition = new(Condition)
