// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/container"
	"github.com/cloudfoundry-incubator/ducati-daemon/models"
)

type Creator struct {
	SetupStub        func(container.CreatorConfig) (models.Container, error)
	setupMutex       sync.RWMutex
	setupArgsForCall []struct {
		arg1 container.CreatorConfig
	}
	setupReturns struct {
		result1 models.Container
		result2 error
	}
}

func (fake *Creator) Setup(arg1 container.CreatorConfig) (models.Container, error) {
	fake.setupMutex.Lock()
	fake.setupArgsForCall = append(fake.setupArgsForCall, struct {
		arg1 container.CreatorConfig
	}{arg1})
	fake.setupMutex.Unlock()
	if fake.SetupStub != nil {
		return fake.SetupStub(arg1)
	} else {
		return fake.setupReturns.result1, fake.setupReturns.result2
	}
}

func (fake *Creator) SetupCallCount() int {
	fake.setupMutex.RLock()
	defer fake.setupMutex.RUnlock()
	return len(fake.setupArgsForCall)
}

func (fake *Creator) SetupArgsForCall(i int) container.CreatorConfig {
	fake.setupMutex.RLock()
	defer fake.setupMutex.RUnlock()
	return fake.setupArgsForCall[i].arg1
}

func (fake *Creator) SetupReturns(result1 models.Container, result2 error) {
	fake.SetupStub = nil
	fake.setupReturns = struct {
		result1 models.Container
		result2 error
	}{result1, result2}
}
