// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/models"
)

type DelController struct {
	DelStub        func(models.CNIDelPayload) error
	delMutex       sync.RWMutex
	delArgsForCall []struct {
		arg1 models.CNIDelPayload
	}
	delReturns struct {
		result1 error
	}
}

func (fake *DelController) Del(arg1 models.CNIDelPayload) error {
	fake.delMutex.Lock()
	fake.delArgsForCall = append(fake.delArgsForCall, struct {
		arg1 models.CNIDelPayload
	}{arg1})
	fake.delMutex.Unlock()
	if fake.DelStub != nil {
		return fake.DelStub(arg1)
	} else {
		return fake.delReturns.result1
	}
}

func (fake *DelController) DelCallCount() int {
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	return len(fake.delArgsForCall)
}

func (fake *DelController) DelArgsForCall(i int) models.CNIDelPayload {
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	return fake.delArgsForCall[i].arg1
}

func (fake *DelController) DelReturns(result1 error) {
	fake.DelStub = nil
	fake.delReturns = struct {
		result1 error
	}{result1}
}
