// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/container"
)

type Deletor struct {
	DeleteStub        func(deletorConfig container.DeletorConfig) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		deletorConfig container.DeletorConfig
	}
	deleteReturns struct {
		result1 error
	}
}

func (fake *Deletor) Delete(deletorConfig container.DeletorConfig) error {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		deletorConfig container.DeletorConfig
	}{deletorConfig})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(deletorConfig)
	} else {
		return fake.deleteReturns.result1
	}
}

func (fake *Deletor) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *Deletor) DeleteArgsForCall(i int) container.DeletorConfig {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].deletorConfig
}

func (fake *Deletor) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}
