// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/sandbox"
	"github.com/tedsuo/ifrit"
)

type Invoker struct {
	InvokeStub        func(ifrit.Runner) ifrit.Process
	invokeMutex       sync.RWMutex
	invokeArgsForCall []struct {
		arg1 ifrit.Runner
	}
	invokeReturns struct {
		result1 ifrit.Process
	}
}

func (fake *Invoker) Invoke(arg1 ifrit.Runner) ifrit.Process {
	fake.invokeMutex.Lock()
	fake.invokeArgsForCall = append(fake.invokeArgsForCall, struct {
		arg1 ifrit.Runner
	}{arg1})
	fake.invokeMutex.Unlock()
	if fake.InvokeStub != nil {
		return fake.InvokeStub(arg1)
	} else {
		return fake.invokeReturns.result1
	}
}

func (fake *Invoker) InvokeCallCount() int {
	fake.invokeMutex.RLock()
	defer fake.invokeMutex.RUnlock()
	return len(fake.invokeArgsForCall)
}

func (fake *Invoker) InvokeArgsForCall(i int) ifrit.Runner {
	fake.invokeMutex.RLock()
	defer fake.invokeMutex.RUnlock()
	return fake.invokeArgsForCall[i].arg1
}

func (fake *Invoker) InvokeReturns(result1 ifrit.Process) {
	fake.InvokeStub = nil
	fake.invokeReturns = struct {
		result1 ifrit.Process
	}{result1}
}

var _ sandbox.Invoker = new(Invoker)
