// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/handlers"
	"github.com/pivotal-golang/lager"
)

type Logger struct {
	ErrorStub        func(action string, err error, data ...lager.Data)
	errorMutex       sync.RWMutex
	errorArgsForCall []struct {
		action string
		err    error
		data   []lager.Data
	}
}

func (fake *Logger) Error(action string, err error, data ...lager.Data) {
	fake.errorMutex.Lock()
	fake.errorArgsForCall = append(fake.errorArgsForCall, struct {
		action string
		err    error
		data   []lager.Data
	}{action, err, data})
	fake.errorMutex.Unlock()
	if fake.ErrorStub != nil {
		fake.ErrorStub(action, err, data...)
	}
}

func (fake *Logger) ErrorCallCount() int {
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	return len(fake.errorArgsForCall)
}

func (fake *Logger) ErrorArgsForCall(i int) (string, error, []lager.Data) {
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	return fake.errorArgsForCall[i].action, fake.errorArgsForCall[i].err, fake.errorArgsForCall[i].data
}

var _ handlers.Logger = new(Logger)
