// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/lib/namespace"
)

type Repository struct {
	GetStub        func(name string) (namespace.Namespace, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		name string
	}
	getReturns struct {
		result1 namespace.Namespace
		result2 error
	}
	CreateStub        func(name string) (namespace.Namespace, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		name string
	}
	createReturns struct {
		result1 namespace.Namespace
		result2 error
	}
	DestroyStub        func(ns namespace.Namespace) error
	destroyMutex       sync.RWMutex
	destroyArgsForCall []struct {
		ns namespace.Namespace
	}
	destroyReturns struct {
		result1 error
	}
	PathOfStub        func(path string) string
	pathOfMutex       sync.RWMutex
	pathOfArgsForCall []struct {
		path string
	}
	pathOfReturns struct {
		result1 string
	}
}

func (fake *Repository) Get(name string) (namespace.Namespace, error) {
	fake.getMutex.Lock()
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		name string
	}{name})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(name)
	} else {
		return fake.getReturns.result1, fake.getReturns.result2
	}
}

func (fake *Repository) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *Repository) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].name
}

func (fake *Repository) GetReturns(result1 namespace.Namespace, result2 error) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 namespace.Namespace
		result2 error
	}{result1, result2}
}

func (fake *Repository) Create(name string) (namespace.Namespace, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		name string
	}{name})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(name)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *Repository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *Repository) CreateArgsForCall(i int) string {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].name
}

func (fake *Repository) CreateReturns(result1 namespace.Namespace, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 namespace.Namespace
		result2 error
	}{result1, result2}
}

func (fake *Repository) Destroy(ns namespace.Namespace) error {
	fake.destroyMutex.Lock()
	fake.destroyArgsForCall = append(fake.destroyArgsForCall, struct {
		ns namespace.Namespace
	}{ns})
	fake.destroyMutex.Unlock()
	if fake.DestroyStub != nil {
		return fake.DestroyStub(ns)
	} else {
		return fake.destroyReturns.result1
	}
}

func (fake *Repository) DestroyCallCount() int {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return len(fake.destroyArgsForCall)
}

func (fake *Repository) DestroyArgsForCall(i int) namespace.Namespace {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return fake.destroyArgsForCall[i].ns
}

func (fake *Repository) DestroyReturns(result1 error) {
	fake.DestroyStub = nil
	fake.destroyReturns = struct {
		result1 error
	}{result1}
}

func (fake *Repository) PathOf(path string) string {
	fake.pathOfMutex.Lock()
	fake.pathOfArgsForCall = append(fake.pathOfArgsForCall, struct {
		path string
	}{path})
	fake.pathOfMutex.Unlock()
	if fake.PathOfStub != nil {
		return fake.PathOfStub(path)
	} else {
		return fake.pathOfReturns.result1
	}
}

func (fake *Repository) PathOfCallCount() int {
	fake.pathOfMutex.RLock()
	defer fake.pathOfMutex.RUnlock()
	return len(fake.pathOfArgsForCall)
}

func (fake *Repository) PathOfArgsForCall(i int) string {
	fake.pathOfMutex.RLock()
	defer fake.pathOfMutex.RUnlock()
	return fake.pathOfArgsForCall[i].path
}

func (fake *Repository) PathOfReturns(result1 string) {
	fake.PathOfStub = nil
	fake.pathOfReturns = struct {
		result1 string
	}{result1}
}

var _ namespace.Repository = new(Repository)
