// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/ipam"
)

type StoreFactory struct {
	CreateStub        func(path string) (ipam.AllocatorStore, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		path string
	}
	createReturns struct {
		result1 ipam.AllocatorStore
		result2 error
	}
}

func (fake *StoreFactory) Create(path string) (ipam.AllocatorStore, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		path string
	}{path})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(path)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *StoreFactory) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *StoreFactory) CreateArgsForCall(i int) string {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].path
}

func (fake *StoreFactory) CreateReturns(result1 ipam.AllocatorStore, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 ipam.AllocatorStore
		result2 error
	}{result1, result2}
}
