// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/lib/namespace"
	"github.com/cloudfoundry-incubator/ducati-daemon/watcher"
)

type MissWatcher struct {
	StartMonitorStub        func(ns namespace.Namespace, vxlanLinkName string) error
	startMonitorMutex       sync.RWMutex
	startMonitorArgsForCall []struct {
		ns            namespace.Namespace
		vxlanLinkName string
	}
	startMonitorReturns struct {
		result1 error
	}
	StopMonitorStub        func(ns namespace.Namespace) error
	stopMonitorMutex       sync.RWMutex
	stopMonitorArgsForCall []struct {
		ns namespace.Namespace
	}
	stopMonitorReturns struct {
		result1 error
	}
}

func (fake *MissWatcher) StartMonitor(ns namespace.Namespace, vxlanLinkName string) error {
	fake.startMonitorMutex.Lock()
	fake.startMonitorArgsForCall = append(fake.startMonitorArgsForCall, struct {
		ns            namespace.Namespace
		vxlanLinkName string
	}{ns, vxlanLinkName})
	fake.startMonitorMutex.Unlock()
	if fake.StartMonitorStub != nil {
		return fake.StartMonitorStub(ns, vxlanLinkName)
	} else {
		return fake.startMonitorReturns.result1
	}
}

func (fake *MissWatcher) StartMonitorCallCount() int {
	fake.startMonitorMutex.RLock()
	defer fake.startMonitorMutex.RUnlock()
	return len(fake.startMonitorArgsForCall)
}

func (fake *MissWatcher) StartMonitorArgsForCall(i int) (namespace.Namespace, string) {
	fake.startMonitorMutex.RLock()
	defer fake.startMonitorMutex.RUnlock()
	return fake.startMonitorArgsForCall[i].ns, fake.startMonitorArgsForCall[i].vxlanLinkName
}

func (fake *MissWatcher) StartMonitorReturns(result1 error) {
	fake.StartMonitorStub = nil
	fake.startMonitorReturns = struct {
		result1 error
	}{result1}
}

func (fake *MissWatcher) StopMonitor(ns namespace.Namespace) error {
	fake.stopMonitorMutex.Lock()
	fake.stopMonitorArgsForCall = append(fake.stopMonitorArgsForCall, struct {
		ns namespace.Namespace
	}{ns})
	fake.stopMonitorMutex.Unlock()
	if fake.StopMonitorStub != nil {
		return fake.StopMonitorStub(ns)
	} else {
		return fake.stopMonitorReturns.result1
	}
}

func (fake *MissWatcher) StopMonitorCallCount() int {
	fake.stopMonitorMutex.RLock()
	defer fake.stopMonitorMutex.RUnlock()
	return len(fake.stopMonitorArgsForCall)
}

func (fake *MissWatcher) StopMonitorArgsForCall(i int) namespace.Namespace {
	fake.stopMonitorMutex.RLock()
	defer fake.stopMonitorMutex.RUnlock()
	return fake.stopMonitorArgsForCall[i].ns
}

func (fake *MissWatcher) StopMonitorReturns(result1 error) {
	fake.StopMonitorStub = nil
	fake.stopMonitorReturns = struct {
		result1 error
	}{result1}
}

var _ watcher.MissWatcher = new(MissWatcher)
