// This file was generated by counterfeiter
package fakes

import (
	"net"
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/commands"
)

type HardwareAddresser struct {
	HardwareAddressStub        func(linkName string) (net.HardwareAddr, error)
	hardwareAddressMutex       sync.RWMutex
	hardwareAddressArgsForCall []struct {
		linkName string
	}
	hardwareAddressReturns struct {
		result1 net.HardwareAddr
		result2 error
	}
}

func (fake *HardwareAddresser) HardwareAddress(linkName string) (net.HardwareAddr, error) {
	fake.hardwareAddressMutex.Lock()
	fake.hardwareAddressArgsForCall = append(fake.hardwareAddressArgsForCall, struct {
		linkName string
	}{linkName})
	fake.hardwareAddressMutex.Unlock()
	if fake.HardwareAddressStub != nil {
		return fake.HardwareAddressStub(linkName)
	} else {
		return fake.hardwareAddressReturns.result1, fake.hardwareAddressReturns.result2
	}
}

func (fake *HardwareAddresser) HardwareAddressCallCount() int {
	fake.hardwareAddressMutex.RLock()
	defer fake.hardwareAddressMutex.RUnlock()
	return len(fake.hardwareAddressArgsForCall)
}

func (fake *HardwareAddresser) HardwareAddressArgsForCall(i int) string {
	fake.hardwareAddressMutex.RLock()
	defer fake.hardwareAddressMutex.RUnlock()
	return fake.hardwareAddressArgsForCall[i].linkName
}

func (fake *HardwareAddresser) HardwareAddressReturns(result1 net.HardwareAddr, result2 error) {
	fake.HardwareAddressStub = nil
	fake.hardwareAddressReturns = struct {
		result1 net.HardwareAddr
		result2 error
	}{result1, result2}
}

var _ commands.HardwareAddresser = new(HardwareAddresser)
