// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/commands"
)

type SetUpper struct {
	SetUpStub        func(name string) error
	setUpMutex       sync.RWMutex
	setUpArgsForCall []struct {
		name string
	}
	setUpReturns struct {
		result1 error
	}
}

func (fake *SetUpper) SetUp(name string) error {
	fake.setUpMutex.Lock()
	fake.setUpArgsForCall = append(fake.setUpArgsForCall, struct {
		name string
	}{name})
	fake.setUpMutex.Unlock()
	if fake.SetUpStub != nil {
		return fake.SetUpStub(name)
	} else {
		return fake.setUpReturns.result1
	}
}

func (fake *SetUpper) SetUpCallCount() int {
	fake.setUpMutex.RLock()
	defer fake.setUpMutex.RUnlock()
	return len(fake.setUpArgsForCall)
}

func (fake *SetUpper) SetUpArgsForCall(i int) string {
	fake.setUpMutex.RLock()
	defer fake.setUpMutex.RUnlock()
	return fake.setUpArgsForCall[i].name
}

func (fake *SetUpper) SetUpReturns(result1 error) {
	fake.SetUpStub = nil
	fake.setUpReturns = struct {
		result1 error
	}{result1}
}

var _ commands.SetUpper = new(SetUpper)
