// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/ducati-daemon/commands"
)

type VethFactory struct {
	CreateVethStub        func(name, peerName string, mtu int) error
	createVethMutex       sync.RWMutex
	createVethArgsForCall []struct {
		name     string
		peerName string
		mtu      int
	}
	createVethReturns struct {
		result1 error
	}
}

func (fake *VethFactory) CreateVeth(name string, peerName string, mtu int) error {
	fake.createVethMutex.Lock()
	fake.createVethArgsForCall = append(fake.createVethArgsForCall, struct {
		name     string
		peerName string
		mtu      int
	}{name, peerName, mtu})
	fake.createVethMutex.Unlock()
	if fake.CreateVethStub != nil {
		return fake.CreateVethStub(name, peerName, mtu)
	} else {
		return fake.createVethReturns.result1
	}
}

func (fake *VethFactory) CreateVethCallCount() int {
	fake.createVethMutex.RLock()
	defer fake.createVethMutex.RUnlock()
	return len(fake.createVethArgsForCall)
}

func (fake *VethFactory) CreateVethArgsForCall(i int) (string, string, int) {
	fake.createVethMutex.RLock()
	defer fake.createVethMutex.RUnlock()
	return fake.createVethArgsForCall[i].name, fake.createVethArgsForCall[i].peerName, fake.createVethArgsForCall[i].mtu
}

func (fake *VethFactory) CreateVethReturns(result1 error) {
	fake.CreateVethStub = nil
	fake.createVethReturns = struct {
		result1 error
	}{result1}
}

var _ commands.VethFactory = new(VethFactory)
